### ISSUE TITLE
Need Project Description 

### ISSUE THREAD

**Issue by aaryadev** [phpsql/phpsqlcore#1]
HI  @eriksank  need proper description and implementations method of project.
or Wiki also works fine.

**Comment by eriksank** [comment]
We have a starting point now: https://github.com/phpsql/phpsqlcore/wiki
Of course, that page is just the beginning. It is the discussions in #2 #3 #4 that should allow us to form sub-teams for these sub-projects. I hope we can get there soon! Thanks for reminding me! I will close this issue for now.

**Comment by terdia** [comment]
What an opportunity to learn and contribute to open source. Strong argument against committees.
